#!/usr/bin/env bash
hash uv 2>/dev/null || { echo >&2 "error: uv not found"; exit 1; }
hash yq 2>/dev/null || { echo >&2 "error: yq not found"; exit 1; }
hash curl 2>/dev/null || { echo >&2 "error: curl not found"; exit 1; }

set -e

BASE_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
REPO_TMP=$(mktemp -d -p $BASE_DIR)
trap 'rm -rf "$REPO_TMP"' EXIT

(
    cd "$BASE_DIR"

    if [ ! -f flatpak-cargo-generator.py ]; then
        echo -n "Downloading flatpak-cargo-generator...  "
        curl -s -O https://raw.githubusercontent.com/flatpak/flatpak-builder-tools/refs/heads/master/cargo/flatpak-cargo-generator.py
        echo "✅"
    fi
    if [ ! -f flatpak-dotnet-generator.py ]; then
        echo -n "Downloading flatpak-dotnet-generator... "
        curl -s -O https://raw.githubusercontent.com/flatpak/flatpak-builder-tools/refs/heads/master/dotnet/flatpak-dotnet-generator.py
        echo "✅"
    fi

    repo=$(yq '(.modules[] | select(.name == "mind-work-ai-studio")).sources[0] | .url' org.MindWorkAI.AIStudio.yml)
    commit=$(yq '(.modules[] | select(.name == "mind-work-ai-studio")).sources[0] | .commit' org.MindWorkAI.AIStudio.yml)

    echo -n "Cloning $repo / $commit... "
    (
        cd $REPO_TMP
        git init
        git remote add origin $repo
        git fetch --depth 1 origin $commit
        git checkout FETCH_HEAD
        patch -p1 < $BASE_DIR/patches/skip-dependency-download.patch
    ) &> /dev/null
    echo "✅"

    uv run --with aiohttp flatpak-cargo-generator.py "$REPO_TMP/runtime/Cargo.lock" -o "cargo-sources.json"
    uv run --with aiohttp flatpak-dotnet-generator.py -f 25.08 -d 9 "dotnet-sources.json" \
        "$REPO_TMP/app/Build/Build Script.csproj" \
        "$REPO_TMP/app/MindWork AI Studio/MindWork AI Studio.csproj" \
        "$REPO_TMP/app/SharedTools/SharedTools.csproj" \
        "$REPO_TMP/app/SourceCodeRules/SourceCodeRules/SourceCodeRules.csproj" --dotnet-args --no-cache

    find $REPO_TMP -mindepth 1 -delete

    repo=$(yq '(.modules[] | select(.name == "tauri-cli")).sources[0] | .url' org.MindWorkAI.AIStudio.yml)
    commit=$(yq '(.modules[] | select(.name == "tauri-cli")).sources[0] | .tag' org.MindWorkAI.AIStudio.yml)

    echo -n "Cloning $repo / $commit... "
    (
        cd $REPO_TMP
        git init
        git remote add origin $repo
        git fetch --depth 1 origin $commit
        git checkout FETCH_HEAD
    ) &> /dev/null
    echo "✅"

    uv run --with aiohttp flatpak-cargo-generator.py "$REPO_TMP/Cargo.lock" -o "tauri-cli-sources.json"
)
