name: Build Flatpak

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  flatpak:
    name: Build & Bundle Flatpak
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-50
      options: --privileged

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build AIStudio flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: AIStudio.flatpak
          manifest-path: org.MindWorkAI.AIStudio.yml
          cache-id: ai-studio
          cache: true
          branch: stable

      - name: Prepare plugin builds
        run: flatpak install --system -y --noninteractive ./AIStudio.flatpak

      - name: Build Pandoc plugin
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: AIStudio-plugin-pandoc.flatpak
          manifest-path: plugins/pandoc/org.MindWorkAI.AIStudio.plugin.pandoc.yml
          cache-id: pandoc-plugin
          cache: true
