name: Build Flatpak

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  flatpak:
    name: Build & Bundle Flatpak
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-50
      options: --privileged

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: AIStudio.flatpak
          manifest-path: org.MindWorkAI.AIStudio.yml
          cache-id: ${{ github.ref }}
          cache: true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: flatpak-bundle
          path: AIStudio.flatpak
